name: CI Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    # Do not run if the only files changed cannot affect the build
    paths-ignore:
      - "**.md"
      - "**.MD"
      - "LICENSE"

jobs:
  GNU:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15, macos-11]
        compiler: [gfortran-8, gfortran-9, gfortran-10]
        exclude:
          - os: macos-10.15
            compiler: gfortran-8
          - os: macos-11
            compiler: gfortran-8
      fail-fast: false
    env:
      FC: ${{ matrix.compiler }}

    name: ${{ matrix.os }} / ${{ matrix.compiler }}
    steps:
      - name: Install GCC 8 on Ubuntu 20
        if: matrix.os == 'ubuntu-20.04' && matrix.compiler == 'gfortran-8'
        run: |
          sudo apt-get install gfortran-8 -y
      - name: Install GCC 11 on Ubuntu 20
        if: matrix.os == 'ubuntu-20.04' && matrix.compiler == 'gfortran-11'
        run: |
          sudo apt-get install gfortran-11 -y
      - name: Versions
        run: |
          ${FC} --version
          cmake --version
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build gFTL-shared
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_Fortran_COMPILER=${FC}
          make -j$(nproc)

  Nvidia:
    runs-on: ubuntu-20.04
    container: nvcr.io/nvidia/nvhpc:20.11-devel-cuda11.1-ubuntu20.04
    env:
      FC: nvfortran

    name: Nvidia HPC
    steps:
      - name: Versions
        run: |
          ${FC} --version
          cmake --version
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build gFTL-shared
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_Fortran_COMPILER=${FC}
          make -j$(nproc)
