name: CI Tests

on: [push, pull_request]

jobs:
  GNU:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15, macos-11]
        compiler: [gfortran-8, gfortran-9, gfortran-10]
        exclude:
          - os: macos-10.15
            compiler: gfortran-8
          - os: macos-11
            compiler: gfortran-8

      fail-fast: false
    env:
      FC: ${{ matrix.compiler }}
      LANGUAGE: en_US.UTF-8
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      LC_TYPE: en_US.UTF-8

    name: ${{ matrix.os }} / ${{ matrix.compiler }}
    steps:
      - name: Versions
        run: |
          ${FC} --version
          cmake --version
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build gFTL-shared
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_Fortran_COMPILER=${FC}
          make -j$(nproc)

  Nvidia:
    runs-on: ubuntu-20.04
    container: nvcr.io/nvidia/nvhpc:20.11-devel-cuda11.1-ubuntu20.04
    env:
      FC: nvfortran
      LANGUAGE: en_US.UTF-8
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      LC_TYPE: en_US.UTF-8

    name: Nvidia HPC
    steps:
      - name: Versions
        run: |
          ${FC} --version
          cmake --version
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build gFTL-shared
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_Fortran_COMPILER=${FC}
          make -j$(nproc)
